.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH rclone-vfsmount-tray 1  "rclone-vfsmount-tray 0.1.0" 
.SH NAME
rclone\-vfsmount\-tray \- System tray client for rclone VFS mounts
.SH SYNOPSIS
\fBrclone\-vfsmount\-tray\fR [\fB\-\-log\-level\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
System tray client for rclone VFS mounts
.SH OPTIONS
.TP
\fB\-\-log\-level\fR \fI<LEVEL>\fR
Log verbosity. Takes precedence over `RUST_LOG`; defaults to `info`
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
rclone\-vfsmount\-tray\-list(1)
List configured mounts and their state
.TP
rclone\-vfsmount\-tray\-mount(1)
Mount one configured mount
.TP
rclone\-vfsmount\-tray\-unmount(1)
Unmount one mount. Refused while anything is still using it unless `\-\-force`
.TP
rclone\-vfsmount\-tray\-status(1)
Print mount and transfer state
.TP
rclone\-vfsmount\-tray\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.1.0
